### ISSUE TITLE
Ensure that licence scoring done right

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/ipsutin#28]
Viitsitkö katsoa tuon Licence kyselyn pisteytystaulukon myös läpi. Esim mielestäni kysymykseen Do you wish to develop the software further? vastaus: No pitäisi rajata noi restrictive ja permissive ulkopuolelle (?)

**Comment by HRemonen** [comment]
Updated the licenceRecommendations file
