### ISSUE TITLE
Home Page Development

### ISSUE THREAD

**Issue by aysenursrngl** [UniversityOfHelsinkiCS/ipsutin#42]
Home Page of Innotin:

- [x] - Header Large text: "Make a difference in the World"
- [x] - Description text: "Welcome (Name) to your personal space of Innotin. Innotin, you will secure your idea, invention or software and help you to proceed with your patenting process"

![Image](https://github.com/UniversityOfHelsinkiCS/ipsutin/assets/158991816/75095c8b-c936-4de1-b071-4de1457a2095)

**Comment by HRemonen** [comment]
Updated the items to checkbox type
